### ISSUE TITLE
Add logging system

### ISSUE THREAD

**Issue by djaustin** [djaustin/purrito#29]
**Is your feature request related to a problem? Please describe.**
Console.log has had its day

**Describe the solution you'd like**
A proper logging solution like https://www.npmjs.com/package/winston with log levels and all the usual logging niceties

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by RichTeaMan** [comment]
Can we ever see logs from prod? Or does this need to wait until some sort of db integration?

**Comment by djaustin** [comment]
db integration is coming soon but for now we can still look at container logs in dev. Most of the stuff I've worked on has had pretty atrocious logging so happy to be guided
