### ISSUE TITLE
Purrito death simulator

### ISSUE THREAD

**Issue by simon-toogood** [djaustin/purrito#43]
**Is your feature request related to a problem? Please describe.**
Unrealistic Purrito death

**Describe the solution you'd like**
Counter of purrito lives
When user does +do die or similar, decrement lives.
when user does +do live or ressurect, increment lives. 
Tell us how many lives he has left.

When dead, save the time. When ANY command is given to purrito, respond with
"Purrito died [TIME] years ago ... you need to move on."

Incrementing lives will fix purrito. Make sure lives can't go below 0.

**Describe alternatives you've considered**
Impossible

**Additional context**
Meow.

**Comment by djaustin** [comment]
I like it
